import { z } from "zod";

export const productoSchema = z.object({
  id: z.string().optional(),
  sku: z.string().optional().or(z.literal('')), // Optional, autogenerated if empty
  nombre: z.string().min(3, "El nombre debe tener al menos 3 caracteres"),
  descripcion: z.string().optional().or(z.literal('')),
  precioUnitario: z.coerce.number().min(0, "El precio no puede ser negativo"),
  ivaAplicable: z.coerce.number().min(0).max(100).default(15), // ej: 15 para 15%
  activo: z.boolean().default(true),
});

export type ProductoFormData = z.infer<typeof productoSchema>;
